#!/bin/bash
set -euo pipefail

if [[ -f _config.production.yml ]]; then
  echo "_config.production.yml already exists, skipping generation."
  exit 0
fi

if [[ "${GITHUB_REPOSITORY}" == "mindset-dojo/mindset-dojo.github.io" ]]; then
  # Central repo — custom domain
  URL="https://mindset.dojo.center"
  BASEURL="" # No subpath for root domain
else
  # Fork — served from <user>.github.io/<repo-name>
  URL="https://${GITHUB_REPOSITORY_OWNER}.github.io"
  REPO_NAME="$(basename "${GITHUB_REPOSITORY}")"
  BASEURL="/${REPO_NAME}" # Must match actual repo folder name in deployment URL
fi

cat > _config.production.yml <<EOF
# Auto-generated by GitHub Actions
url: "${URL}"
baseurl: "${BASEURL}"
EOF

echo "_config.production.yml generated with:"
cat _config.production.yml
