#!/bin/bash
set -euo pipefail

if [[ -f _config.production.yml ]]; then
  echo "_config.production.yml already exists, skipping generation."
  exit 0
fi

if [[ "${GITHUB_REPOSITORY}" == "mindset-dojo/mindset-dojo.github.io" ]]; then
  URL="https://mindset.dojo.center"
  BASEURL=""
else
  URL="https://${GITHUB_REPOSITORY_OWNER}.github.io"
  BASEURL="/${GITHUB_REPOSITORY#*/}"
fi

cat > _config.production.yml <<EOF
# Auto-generated by GitHub Actions
url: "${URL}"
baseurl: "${BASEURL}"
EOF
