---
mantra: "Don’t Conceal. Contribute."
sections:
  - type: mission
    data:
      mission_rally_suffix_label: ": Living Structure"
      mission_statement_bridge:
        - "We move clarity into form—language, structure, and flow."
        - "We sense friction in the field and adjust with care."
        - "We welcome influence through open, visible practice and reciprocal trust."
  - type: text
    data:
      label: "Project Motivations"
      items:
        - "Our project is a shared practice of simplicity and coherence."
        - "We refine our systems, language, and flow through steady, mindful iteration."
        - "Each contribution strengthens the pattern of fearlessness in form."
  - type: text
    data:
      label: "Contribution Motivations"
      items:
        - "Make contribution as natural as conversation."
        - "Create infrastructure that teaches as it grows."
        - "Invite courage through transparency and simplicity."
  - type: text
    data:
      label: "Contribution Invitations"
      items:
        - "You sense where the system isn’t flowing."
        - "You refactor a phrase or function toward clarity."
        - "You offer a pattern that helps others move with ease."
        - "You make reciprocity visible—through reviews, documentation, or mentorship."
  - type: quote
    data:
      text: "Ideation is fun, pull requests invite influence."
  - type: designations
    data:
      label: "Leadership Designations"
      intention_label: "Intention"
      aspects_label: "Aspects"
      items:
        - label: "(Domain-Specific) Cultivator"
          intention: "Strengthen, clarify, and amplify the mission"
          aspects:
            - label: "Join Cultivator Circle regularly"
            - label: "Contribute to expertise in a mutually beneficial way"
            - label: "Green Level+, vouched for by existing Cultivator(s)"
        - label: "Project Cultivator"
          intention: "Guide, harmonize, and model training authorship"
          aspects:
            - label: "Lead Cultivator Circle sessions regularly"
            - label: "Cultivate project culture and brand coherence"
            - label: "Black Level, Zen Leadership Instructor intention"
  - type: authors
    data:
      leadership_flow:
        label: "⛩️🪴 System Gardeners"
        designation_type: program
        limit: 8
  - type: ctas
    data:
      items:
        - label: "Inspect the Roots"
          ref: repo
---
