---
mantra: "Don’t Control. Co-Create."
mantra_mark: "Co-Create."
description: |
  An open-source dojo — where presence meets practice through shared stewardship.
  The project evolves through reciprocity, clarity, and the collective rhythm of
  those actively training. Open-source becomes part of the training game itself:
  nothing is distant, siloed, or hidden.
sections:
  - type: text
    data:
      label: "Dojo Infrastructure: Open Source’d"
      items:
        - "The Project is the living infrastructure of Mindset Dojo — a training ground for co-creation and presence under real conditions."
        - "It grows through contributions from those practicing and refining their craft."
        - "Hosted openly on GitHub — transparency, rhythm, and relational integrity guide its evolution."
  - type: text
    data:
      label: "Open Source as Practice"
      items:
        - "Every commit is a calibration toward coherence — a move in the training game."
        - "Every refactor is a bow to clarity."
        - "We treat the codebase as we treat the mat — with presence, precision, and respect."
  - type: text
    data:
      label: "Ways to Contribute"
      items:
        - "Refactor language, structure, or function toward clarity and coherence."
        - "Offer patterns, practices, or feedback that help others move with ease."
        - "Model reciprocity through guidance, review, and mentorship — the inverse of distancing."
  - type: quote
    data:
      text: "Ideation is play; contribution is practice."
  - type: principles
    data:
      principles_title: "Engagement Principles"
      principles_groups:
        - "project"
  - type: designations
    data:
      label: "Leadership Designations"
      items:
        - label: "(Domain-Focused) Cultivator"
          intentions:
            - label: "Strengthen, clarify, and amplify the mission"
            - label: "Join Cultivator Circle regularly"
            - label: "Contribute expertise in a mutually beneficial way"
            - label: "Green Level+, vouched for by existing Cultivator(s)"
        - label: "(Organizationally-Focused) Cultivator"
          intentions:
            - label: "Guide, harmonize, and model training authorship"
            - label: "Lead Cultivator Circle sessions regularly"
            - label: "Cultivate project culture and brand coherence"
            - label: "Black Level, vouched for by existing Cultivator(s)"
  - type: authors
    data:
      leadership_flow:
        label: "⛩️💫 Cultivators"
        designation_type: project
        limit: 8
  - type: ctas
    data:
      items:
        - label: "Tend the Garden"
          ref: repo
...
