---
mantra: "Don’t Control. Co-Create."
mantra_mark: "Co-Create."
description: "An open-source dojo — where presence meets practice through shared stewardship. Structure evolves through care, contribution, and rhythm as we train together."
sections:
  - type: text
    data:
      label: "Dojo Infrastructure: Open Source’d"
      items:
        - "The Project is the living infrastructure of Mindset Dojo — a training ground for co-creation itself."
        - "It grows through contributions from those actively training and refining their craft."
        - "Hosted openly on GitHub — transparency, reciprocity, and rhythm guide its evolution."
  - type: text
    data:
      label: "Open Source as Practice"
      items:
        - "Every commit is a calibration."
        - "Every refactor, a bow of respect toward clarity."
        - "We treat the codebase as we treat the mat — with presence and precision."
  - type: text
    data:
      label: "Ways to Contribute"
      items:
        - "Refactor language, structure, or function toward greater clarity."
        - "Offer patterns, practices, or feedback that help others move with ease."
        - "Model reciprocity through guidance, review, and mentorship."
  - type: quote
    data:
      text: "Ideation is play; contribution is practice."
  - type: list
    data:
      label: "Engagement Principles"
      items:
        - id: transparency
          label: "Transparency Invites Trust"
          description: "Openness in process, intent, and communication turns control into shared clarity."
        - id: contribution
          label: "Contribution Shapes Coherence"
          description: "Each act of authorship refines the whole; shared care turns complexity to rhythm."
        - id: presence
          label: "Presence Tends the Form"
          description: "We tend the system as a living garden — pruning, nurturing, redesigning with awareness."
  - type: designations
    data:
      label: "Leadership Designations"
      intention_label: "Intention"
      aspects_label: "Aspects"
      items:
        - label: "(Domain-Focused) Cultivator"
          intention: "Strengthen, clarify, and amplify the mission"
          aspects:
            - label: "Join Cultivator Circle regularly"
            - label: "Contribute expertise in a mutually beneficial way"
            - label: "Green Level+, vouched for by existing Cultivator(s)"
        - label: "(Organizationally-Focused) Cultivator"
          intention: "Guide, harmonize, and model training authorship"
          aspects:
            - label: "Lead Cultivator Circle sessions regularly"
            - label: "Cultivate project culture and brand coherence"
            - label: "Black Level, vouched for by existing Cultivator(s)"
  - type: authors
    data:
      leadership_flow:
        label: "⛩️💫 Cultivators"
        designation_type: project
        limit: 8
  - type: ctas
    data:
      items:
        - label: "Tend the Garden"
          ref: repo
...
